// source: sipc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.kr.jclab.sipc.ClientHelloPayload', null, global);
goog.exportSymbol('proto.kr.jclab.sipc.ConnectInfo', null, global);
goog.exportSymbol('proto.kr.jclab.sipc.TransportType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kr.jclab.sipc.ConnectInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kr.jclab.sipc.ConnectInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kr.jclab.sipc.ConnectInfo.displayName = 'proto.kr.jclab.sipc.ConnectInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kr.jclab.sipc.ClientHelloPayload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kr.jclab.sipc.ClientHelloPayload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kr.jclab.sipc.ClientHelloPayload.displayName = 'proto.kr.jclab.sipc.ClientHelloPayload';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kr.jclab.sipc.ConnectInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.kr.jclab.sipc.ConnectInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kr.jclab.sipc.ConnectInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kr.jclab.sipc.ConnectInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    connectionId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    transportType: jspb.Message.getFieldWithDefault(msg, 2, 0),
    transportAddress: jspb.Message.getFieldWithDefault(msg, 3, ""),
    publicKey: msg.getPublicKey_asB64(),
    allowReconnect: jspb.Message.getBooleanFieldWithDefault(msg, 11, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kr.jclab.sipc.ConnectInfo}
 */
proto.kr.jclab.sipc.ConnectInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kr.jclab.sipc.ConnectInfo;
  return proto.kr.jclab.sipc.ConnectInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kr.jclab.sipc.ConnectInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kr.jclab.sipc.ConnectInfo}
 */
proto.kr.jclab.sipc.ConnectInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setConnectionId(value);
      break;
    case 2:
      var value = /** @type {!proto.kr.jclab.sipc.TransportType} */ (reader.readEnum());
      msg.setTransportType(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransportAddress(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setPublicKey(value);
      break;
    case 11:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAllowReconnect(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kr.jclab.sipc.ConnectInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kr.jclab.sipc.ConnectInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kr.jclab.sipc.ConnectInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kr.jclab.sipc.ConnectInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConnectionId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTransportType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getTransportAddress();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPublicKey_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
  f = message.getAllowReconnect();
  if (f) {
    writer.writeBool(
      11,
      f
    );
  }
};


/**
 * optional string connection_id = 1;
 * @return {string}
 */
proto.kr.jclab.sipc.ConnectInfo.prototype.getConnectionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.kr.jclab.sipc.ConnectInfo} returns this
 */
proto.kr.jclab.sipc.ConnectInfo.prototype.setConnectionId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional TransportType transport_type = 2;
 * @return {!proto.kr.jclab.sipc.TransportType}
 */
proto.kr.jclab.sipc.ConnectInfo.prototype.getTransportType = function() {
  return /** @type {!proto.kr.jclab.sipc.TransportType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.kr.jclab.sipc.TransportType} value
 * @return {!proto.kr.jclab.sipc.ConnectInfo} returns this
 */
proto.kr.jclab.sipc.ConnectInfo.prototype.setTransportType = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string transport_address = 3;
 * @return {string}
 */
proto.kr.jclab.sipc.ConnectInfo.prototype.getTransportAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.kr.jclab.sipc.ConnectInfo} returns this
 */
proto.kr.jclab.sipc.ConnectInfo.prototype.setTransportAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional bytes public_key = 4;
 * @return {!(string|Uint8Array)}
 */
proto.kr.jclab.sipc.ConnectInfo.prototype.getPublicKey = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes public_key = 4;
 * This is a type-conversion wrapper around `getPublicKey()`
 * @return {string}
 */
proto.kr.jclab.sipc.ConnectInfo.prototype.getPublicKey_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getPublicKey()));
};


/**
 * optional bytes public_key = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getPublicKey()`
 * @return {!Uint8Array}
 */
proto.kr.jclab.sipc.ConnectInfo.prototype.getPublicKey_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getPublicKey()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.kr.jclab.sipc.ConnectInfo} returns this
 */
proto.kr.jclab.sipc.ConnectInfo.prototype.setPublicKey = function(value) {
  return jspb.Message.setProto3BytesField(this, 4, value);
};


/**
 * optional bool allow_reconnect = 11;
 * @return {boolean}
 */
proto.kr.jclab.sipc.ConnectInfo.prototype.getAllowReconnect = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 11, false));
};


/**
 * @param {boolean} value
 * @return {!proto.kr.jclab.sipc.ConnectInfo} returns this
 */
proto.kr.jclab.sipc.ConnectInfo.prototype.setAllowReconnect = function(value) {
  return jspb.Message.setProto3BooleanField(this, 11, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kr.jclab.sipc.ClientHelloPayload.prototype.toObject = function(opt_includeInstance) {
  return proto.kr.jclab.sipc.ClientHelloPayload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kr.jclab.sipc.ClientHelloPayload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kr.jclab.sipc.ClientHelloPayload.toObject = function(includeInstance, msg) {
  var f, obj = {
    connectionId: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kr.jclab.sipc.ClientHelloPayload}
 */
proto.kr.jclab.sipc.ClientHelloPayload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kr.jclab.sipc.ClientHelloPayload;
  return proto.kr.jclab.sipc.ClientHelloPayload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kr.jclab.sipc.ClientHelloPayload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kr.jclab.sipc.ClientHelloPayload}
 */
proto.kr.jclab.sipc.ClientHelloPayload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setConnectionId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kr.jclab.sipc.ClientHelloPayload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kr.jclab.sipc.ClientHelloPayload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kr.jclab.sipc.ClientHelloPayload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kr.jclab.sipc.ClientHelloPayload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConnectionId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string connection_id = 1;
 * @return {string}
 */
proto.kr.jclab.sipc.ClientHelloPayload.prototype.getConnectionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.kr.jclab.sipc.ClientHelloPayload} returns this
 */
proto.kr.jclab.sipc.ClientHelloPayload.prototype.setConnectionId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * @enum {number}
 */
proto.kr.jclab.sipc.TransportType = {
  KUNKNOWN: 0,
  KUNIXDOMAINSOCKET: 1,
  KWINDOWSNAMEDPIPE: 2,
  KTCP: 101
};

goog.object.extend(exports, proto.kr.jclab.sipc);
