name: Build
on: [push, pull_request]
jobs:
  java-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          echo "runner_arch=$(uname -m)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders
      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: "${{ runner.os }}-${{ env.runner_arch }}-buildx-java-${{ github.sha }}"
          restore-keys: "${{ runner.os }}-${{ env.runner_arch }}-buildx-java-"
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/java.Dockerfile
          push: false
          tags: local/temp:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  cpp-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          echo "runner_arch=$(uname -m)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders
      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: "${{ runner.os }}-${{ env.runner_arch }}-buildx-cpp-${{ github.sha }}"
          restore-keys: "${{ runner.os }}-${{ env.runner_arch }}-buildx-cpp-"
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/cpp.Dockerfile
          push: false
          tags: local/temp:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  node-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["12", "14", "16"]
    defaults:
      run:
        working-directory: node
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Environment Variables
        run: |
          echo "runner_arch=$(uname -m)" >> $GITHUB_ENV
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get protobuf version
        run: |
          npm install -g js-yaml
          export protobuf_version="$(node util/get-protobuf-version.js)"
          echo "protobuf_version=${protobuf_version}" | tee -a $GITHUB_ENV
      - name: Setup protobuf
        uses: arduino/setup-protoc@v1
        with:
          version: ${{ env.protobuf_version }}
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
