name: Build
on: [push]
jobs:
  java-build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set Environment Variables
        run: |
          echo "runner_arch=$(uname -m)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'

      - name: Test on Windows
        if: ${{ startsWith(matrix.os, 'win') }}
        run: |
          cd java
          .\gradlew.bat build test
      - name: Test on Linux
        if: ${{ !startsWith(matrix.os, 'win') }}
        run: |
          cd java
          chmod +x gradlew
          ./gradlew build test
  go-build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set Environment Variables
        run: |
          echo "runner_arch=$(uname -m)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Display Go version
        run: go version

      - name: Tests
        run: go test -v ./...
  node-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nodeVersion:
          - 14
          - 16
          - 18
    steps:
      - uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.nodeVersion }}
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{runner.OS}}-build-node_${{ matrix.nodeVersion }}-${{hashFiles('node/yarn.lock')}}
          restore-keys: |
            ${{runner.OS}}-build-node_${{ matrix.nodeVersion }}-*
      - run: |
          cd node
          yarn install
      - run: |
          cd node
          yarn test

